---
title: All I Wanna Buy
timezone: Europe/Paris
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/:categories/:title/"
defaults:
  - scope:
      type: posts
      path: _posts
    values:
      layout: post
      image:
gems:
- jekyll-feed
- jekyll-paginate-v2
exclude:
- Gemfile
- Gemfile.lock
pagination:
  enabled: true
  per_page: 6
autopages:
  enabled: true
  categories:
    permalink: '/:cat'
  tags:
    permalink: '/:tag'