---
title: All I Wanna Buy
timezone: Europe/Paris
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    images:
    - 
permalink: "/:title/"
gems:
- jekyll-feed
- jekyll-paginate-v2
exclude:
- Gemfile
- Gemfile.lock
pagination:
  enabled: true
  per_page: 6
  sort_field: date
  sort_reverse: true
autopages:
  enabled: true
  categories:
    permalink: "/:cat"
    title: :cat
  tags:
    permalink: "/:tag"
    title: :tag
